name: Bug report
description: Something is not working as expected
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to namespace '...'
        2. Open deployment '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behaviour
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: KubeAdjust version
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: k8s
    attributes:
      label: Kubernetes version
      placeholder: "1.29"

  - type: dropdown
    id: metrics
    attributes:
      label: metrics-server installed?
      options:
        - "Yes"
        - "No"
        - "Unknown"

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Backend logs, browser console errors, etc.
      render: shell
