{{- if .Values.oidc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeadjust.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubeadjust.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientSecret: {{ .Values.oidc.clientSecret | quote }}
  sessionSecret: {{ .Values.oidc.sessionSecret | quote }}
  {{- if .Values.oidc.saToken }}
  saToken: {{ .Values.oidc.saToken | quote }}
  {{- end }}
  {{- if .Values.oidc.saTokens }}
  saTokens: {{ .Values.oidc.saTokens | quote }}
  {{- end }}
{{- end }}
